# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your name', max_length=200)),
                ('email', models.CharField(help_text='Please enter your email', max_length=200)),
                ('phone_number', models.CharField(help_text='Please enter your telephone number', max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Please enter your company name', max_length=200)),
                ('address', models.CharField(help_text='Please enter your company address', max_length=400)),
                ('company_number', models.CharField(help_text='Please enter your registered company number (8 digits)', max_length=50, validators=[django.core.validators.RegexValidator(message='The registered company number is a 8 digits number.', regex='^\\d{8}$')])),
                ('business_sector', models.CharField(choices=[('RET', 'Retail'), ('PRO', 'Professional Services'), ('FD', 'Food & Drink'), ('ENT', 'Entertainment')], help_text='Please select your business sector', max_length=100)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Please enter the amount you wish to borrow in GBP')),
                ('days', models.IntegerField(help_text='Please enter the duration of the loan (in days)')),
                ('reason', models.TextField(help_text='Please enter the reason of the loan')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
            ],
        ),
    ]
